<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Flash XML Graphics Format: Version 1.0
	More details here: http://opensource.adobe.com/wiki/display/flexsdk/FXG+1.0+Specification</string>
	<key>fileTypes</key>
	<array>
		<string>fxg</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~F</string>
	<key>name</key>
	<string>FXG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.xml.fxg</string>
	<key>uuid</key>
	<string>C2A3474D-5B90-487E-9221-EE1A1870D3D6</string>
</dict>
</plist>
